Document: libfslvpuwrap
Title: Debian libfslvpuwrap Manual
Author: <insert document author here>
Abstract: This manual describes what libfslvpuwrap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfslvpuwrap/libfslvpuwrap.sgml.gz

Format: postscript
Files: /usr/share/doc/libfslvpuwrap/libfslvpuwrap.ps.gz

Format: text
Files: /usr/share/doc/libfslvpuwrap/libfslvpuwrap.text.gz

Format: HTML
Index: /usr/share/doc/libfslvpuwrap/html/index.html
Files: /usr/share/doc/libfslvpuwrap/html/*.html
